name: subway
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  dio: ^5.11.1
  dio_smart_retry: ^7.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  http: ^1.6.0
  intl: ^0.20.3
  marquee: ^2.3.0
  xml: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/seoul_subway_map_foreigners.png
    - assets/data/Line2_timetable_data.json
    - assets/data/MaglevLine_timetable_data.json
    - assets/data/seoul_stationname_code.json
    - assets/data/gukto_stationname_code.json
    - assets/icons/start_flag.svg
    - assets/icons/destination_flag.svg
    - assets/icons/money_icon.png