import 'package:flutter/material.dart';

const Map<String, String> stationTranslationMap = {
  '4.19민주묘지': '4.19minjumyoji',
  '가능': 'Ganeung',
  '가락시장': 'Garak Market',
  '가산디지털단지': 'Gasan Digital Complex',
  '가양': 'Gayang',
  '가오리': 'gaori',
  '가재울': 'Gajaeul',
  '가정': 'Gajeong',
  '가정중앙시장': 'Gajeong Jungang Market',
  '가좌': 'Gajwa',
  '가천대': 'Kyungwon University',
  '가평': 'Gapyeong',
  '간석': 'Ganseok',
  '간석오거리': 'Ganseogogeori',
  '갈매': 'Galmae',
  '갈산': 'Galsan',
  '강남': 'Gangnam',
  '강남구청': 'Gangnam-gu Office',
  '강남대': 'gangnamdae',
  '강동': 'Gangdong',
  '강동구청': 'Gangdong-gu Office',
  '강매': 'gangmae',
  '강변': 'Gangbyeon',
  '강일': 'gangil',
  '강촌': 'Gangchon',
  '개롱': 'Gaerong',
  '개봉': 'Gaebong',
  '개포동': 'Gaepo-dong',
  '개화': 'Gaehwa',
  '개화산': 'Gaehwasan',
  '거여': 'Geoyeo',
  '건대입구': 'Konkuk University',
  '걸포북변': 'geolpobukbyeon',
  '검단사거리': 'Geomdan Sageori',
  '검단호수공원': 'Geomdan Lake Park',
  '검단오류': 'Geomdan Oryu',
  '검바위': 'Geombawi',
  '검암': 'Geomam',
  '경기광주': 'Gyeonggi Gwangju',
  '경기도북부청사': 'gyeonggidobukbucheongsa',
  '경마공원': 'Seoul Racecourse Park',
  '경복궁': 'Gyeongbokgung',
  '경인교대입구': 'Gyeongin National University of Education',
  '경전철의정부': 'gyeongjeoncheoluijeongbu',
  '경찰병원': 'National Police Hospital',
  '계산': 'Gyesan',
  '계양': 'Gyeyang',
  '고덕': 'Godeok',
  '고려대': 'Korea University',
  '고속터미널': 'Express Bus Terminal',
  '고잔': 'Gojan',
  '고진': 'gojin',
  '고촌': 'gochon',
  '곡산': 'Goksan',
  '곤제': 'gonje',
  '곤지암': 'Gonjiam',
  '공단': 'Gongdan',
  '공덕': 'Gongdeok',
  '공릉': 'Gongneung',
  '공항시장': 'Airport Market',
  '공항화물청사': 'Incheon International Airport Cargo Terminal',
  '과천': 'Gwacheon',
  '관악': 'Gwanak',
  '관악산': 'gwanaksan',
  '광교': 'Gwanggyo',
  '광교중앙': 'Gwanggyo Jungang',
  '광나루': 'Gwangnaru',
  '광명': 'Gwangmyeong',
  '광명사거리': 'Gwangmyeongsageori',
  '광운대': 'Kwangwoon University',
  '광화문': 'Gwanghwamun',
  '광흥창': 'Gwangheungchang',
  '교대': 'Seoul National University of Education',
  '구래': 'gurae',
  '구로': 'Guro',
  '구로디지털단지': 'Guro Digital Complex',
  '구룡': 'Guryong',
  '구리': 'Guri',
  '구반포': 'Gubanpo',
  '구산': 'Gusan',
  '구성': 'Guseong',
  '구의': 'Guui',
  '구일': 'Guil',
  '구파발': 'Gupabal',
  '국수': 'Guksu',
  '국제업무지구': 'International Business District',
  '국회의사당': 'National Assembly',
  '군자': 'Gunja',
  '군포': 'Gunpo',
  '굴봉산': 'Gulbongsan',
  '굴포천': 'Gulpocheon',
  '굽은다리': 'Gubeundari',
  '귤현': 'Gyulhyeon',
  '금곡': 'Geumgok',
  '금릉': 'Geumneung',
  '금정': 'Geumjeong',
  '금천구청': 'Geumcheon-gu Office',
  '금촌': 'Geumchon',
  '금호': 'Geumho',
  '기흥': 'Giheung',
  '길동': 'Gil-dong',
  '길음': 'Gireum',
  '김량장': 'gimryangjang',
  '김유정': 'Gimyujeong',
  '김포공항': 'Gimpo International Airport',
  '까치산': 'Kkachisan',
  '까치울': 'Kkachiul',
  '낙성대': 'Nakseongdae',
  '남구로': 'Namguro',
  '남동구청': 'Namdong-gu Office',
  '남동인더스파크': 'Namdong Induspark',
  '남부터미널': 'Nambu Bus Terminal',
  '남성': 'Namseong',
  '남영': 'Namyeong',
  '남위례': 'namwirye',
  '남춘천': 'Namchuncheon',
  '남태령': 'Namtaeryeong',
  '남한산성입구': 'Namhansanseong',
  '내방': 'Naebang',
  '노들': 'Nodeul',
  '노량진': 'Noryangjin',
  '노원': 'Nowon',
  '녹번': 'Nokbeon',
  '녹사평': 'Noksapyeong',
  '녹양': 'Nogyang',
  '녹천': 'Nokcheon',
  '논현': 'Nonhyeon',
  '능곡': 'Neunggok',
  '단대오거리': 'Dandaeogeori',
  '달미': 'dalmi',
  '달월': 'dalwol',
  '답십리': 'Dapsimni',
  '당고개': 'Danggogae',
  '당곡': 'danggok',
  '당산': 'Dangsan',
  '당정': 'Dangjeong',
  '대곡': 'Daegok',
  '대공원': 'Seoul Grand Park',
  '대림': 'Daerim',
  '대모산입구': 'Daemosan',
  '대방': 'Daebang',
  '대성리': 'Daeseong-ri',
  '대야미': 'Daeyami',
  '대청': 'Daecheong',
  '대치': 'Daechi',
  '대화': 'Daehwa',
  '대흥': 'Daeheung',
  '덕계': 'Deokgye',
  '덕소': 'Deokso',
  '덕정': 'Deokjeong',
  '도곡': 'Dogok',
  '도농': 'Donong',
  '도림천': 'Dorimcheon',
  '도봉': 'Dobong',
  '도봉산': 'Dobongsan',
  '도심': 'Dosim',
  '도원': 'Dowon',
  '도화': 'Dohwa',
  '독립문': 'Dongnimmun',
  '독바위': 'Dokbawi',
  '독산': 'Doksan',
  '독정': 'Dokjeong',
  '돌곶이': 'Dolgoji',
  '동구릉': 'Donggureung',
  '동대문': 'Dongdaemun',
  '동대문역사문화공원': 'Dongdaemun History & Culture Park',
  '동대입구': 'Dongguk University',
  '동두천': 'Dongducheon',
  '동두천중앙': 'Dongducheonjungang',
  '동막': 'Dongmak',
  '동묘앞': 'Dongmyo',
  '동백': 'dongbaek',
  '동수': 'Dongsu',
  '동암': 'Dongam',
  '동오': 'dongo',
  '동인천': 'Dongincheon',
  '동작': 'Dongjak',
  '동천': 'Dongcheon',
  '동춘': 'Dongchun',
  '동탄': 'dongtan',
  '두정': 'Dujeong',
  '둔전': 'dunjeon',
  '둔촌동': 'Dunchon-dong',
  '둔촌오륜': 'dunchonoryun',
  '등촌': 'Deungchon',
  '디지털미디어시티': 'Digital Media City',
  '뚝섬': 'Ttukseom',
  '뚝섬유원지': 'Ttukseom Resort',
  '마곡': 'Magok',
  '마곡나루': 'magoknaru',
  '마두': 'Madu',
  '마들': 'Madeul',
  '마산': 'masan',
  '마석': 'Maseok',
  '마장': 'Majang',
  '마전': 'Majeon',
  '마천': 'Macheon',
  '마포': 'Mapo',
  '마포구청': 'Mapo-gu Office',
  '만수': 'Mansu',
  '망우': 'Mangu',
  '망원': 'Mangwon',
  '망월사': 'Mangwolsa',
  '망포': 'Mangpo',
  '매교': 'Maegyo',
  '매봉': 'Maebong',
  '매탄권선': 'Maetan-Gwonseon',
  '먹골': 'Meokgol',
  '면목': 'Myeonmok',
  '명동': 'Myeong-dong',
  '명일': 'Myeongil',
  '명지대': 'myeongjidae',
  '명학': 'Myeonghak',
  '모란': 'Moran',
  '모래내시장': 'Moraenae Market',
  '목동': 'Mok-dong',
  '몽촌토성': 'Mongchontoseong',
  '무악재': 'Muakjae',
  '문래': 'Mullae',
  '문산': 'Munsan',
  '문정': 'Munjeong',
  '문학경기장': 'Munhak Sports Complex',
  '미금': 'Migeum',
  '미사': 'misa',
  '미아': 'Mia',
  '미아사거리': 'Miasamgeori',
  '박촌': 'Bakchon',
  '반월': 'Banwol',
  '반포': 'Banpo',
  '발곡': 'balgok',
  '발산': 'Balsan',
  '방배': 'Bangbae',
  '방이': 'Bangi',
  '방학': 'Banghak',
  '방화': 'Banghwa',
  '배방': 'Baebang',
  '백마': 'Baengma',
  '백석': 'Baekseok',
  '백양리': 'Baegyang-ri',
  '백운': 'Baegun',
  '버티고개': 'Beotigogae',
  '범계': 'Beomgye',
  '범골': 'beomgol',
  '별내': 'Byeollae',
  '별내별가람': 'Byeollae Byeolgaram',
  '병점': 'Byeongjeom',
  '보라매': 'Boramae',
  '보라매공원': 'Boramae Park',
  '보라매병원': 'Boramae Hospital',
  '보문': 'Bomun',
  '보산': 'Bosan',
  '보정': 'Bojeong',
  '보평': 'bopyeong',
  '복정': 'Bokjeong',
  '봉명': 'Bongmyeong',
  '봉은사': 'Bongeunsa',
  '봉천': 'Bongcheon',
  '봉화산': 'Bonghwasan',
  '부개': 'Bugae',
  '부발': 'Bubal',
  '부천': 'Bucheon',
  '부천시청': 'Bucheon City Hall',
  '부천종합운동장': 'Bucheon Stadium',
  '부평': 'Bupyeong',
  '부평구청': 'Bupyeong-gu Office',
  '부평삼거리': 'Bupyeongsamgeori',
  '부평시장': 'Bupyeong Market',
  '북한산보국문': 'bukhansanbogukmun',
  '북한산우이': 'bukhansanui',
  '불광': 'Bulgwang',
  '불암산': 'Buramsan',
  '사가정': 'Sagajeong',
  '사당': 'Sadang',
  '사릉': 'Sareung',
  '사리': 'sari',
  '사우': 'sau',
  '사평': 'Sapyeong',
  '산곡': 'sangok',
  '산본': 'Sanbon',
  '산성': 'Sanseong',
  '삼가': 'samga',
  '삼각지': 'Samgakji',
  '삼동': 'Samdong',
  '삼산체육관': 'Samsan Gymnasium',
  '삼성': 'Samseong',
  '삼성중앙': 'Samseongjungang',
  '삼송': 'Samsong',
  '삼양': 'samyang',
  '삼양사거리': 'samyangsageori',
  '삼전': 'samjeon',
  '상갈': 'Sanggal',
  '상계': 'Sanggye',
  '상도': 'Sangdo',
  '상동': 'Sang-dong',
  '상록수': 'Sangnoksu',
  '상봉': 'Sangbong',
  '상수': 'Sangsu',
  '상왕십리': 'Sangwangsimni',
  '상월곡': 'Sangwolgok',
  '상일동': 'Sangil-dong',
  '상천': 'Sangcheon',
  '상현': 'Sanghyeon',
  '새말': 'saemal',
  '새절': 'Saejeol',
  '샘터공원': 'saemteogongwon',
  '샛강': 'Saetgang',
  '서강': 'Seogang',
  '서구청': 'Seo-gu Office',
  '서대문': 'Seodaemun',
  '서동탄': 'Seodongtan',
  '서부여성회관': "West Woman's Community Center",
  '서빙고': 'Seobinggo',
  '서울대벤처타운': 'seouldaebencheotaun',
  '서울대입구': 'Seoul National University',
  '서울숲': 'Seoul Forest',
  '서울역': 'Seoul Station',
  '서울지방병무청': 'seouljibangbyeongmucheong',
  '서원': 'seowon',
  '서정리': 'Seojeong-ri',
  '서초': 'Seocho',
  '서현': 'Seohyeon',
  '석계': 'Seokgye',
  '석남': 'Seongnam',
  '석바위시장': 'Seokbawi Market',
  '석수': 'Seoksu',
  '석천사거리': 'Seokcheon Sageori',
  '석촌': 'Seokchon',
  '석촌고분': 'seokchongobun',
  '선릉': 'Seolleung',
  '선바위': 'Seonbawi',
  '선부': 'seonbu',
  '선유도': 'Seonyudo',
  '선정릉': 'Seonjeongneung',
  '선학': 'Seonhak',
  '성균관대': 'Sungkyunkwan University',
  '성남': 'seongnam',
  '성복': 'Seongbok',
  '성수': 'Seongsu',
  '성신여대입구': "Sungshin Women's University",
  '성환': 'Seonghwan',
  '세류': 'Seryu',
  '세마': 'Sema',
  '세종대왕릉': 'Sejongdaewangneung',
  '센트럴파크': 'Central Park',
  '소래포구': 'Soraepogu',
  '소사': 'Sosa',
  '소새울': 'sosaeul',
  '소요산': 'Soyosan',
  '솔밭공원': 'solbatgongwon',
  '솔샘': 'solsaem',
  '송내': 'Songnae',
  '송도': 'Songdo',
  '송도달빛축제공원': 'songdodalbitchukjegongwon',
  '송산': 'songsan',
  '송정': 'Songjeong',
  '송탄': 'Songtan',
  '송파': 'Songpa',
  '송파나루': 'songpanaru',
  '수내': 'Sunae',
  '수락산': 'Suraksan',
  '수리산': 'Surisan',
  '수색': 'Susaek',
  '수서': 'Suseo',
  '수원': 'Suwon',
  '수원시청': 'Suwon City Hall',
  '수유': 'Suyu',
  '수지구청': 'Suji-gu Office',
  '수진': 'Sujin',
  '숙대입구': "Sookmyung Women's University",
  '숭실대입구': 'Soongsil University',
  '숭의': 'Sungui',
  '시민공원': 'Citizens Park',
  '시우': 'siu',
  '시청': 'City Hall',
  '시청·용인대': 'sicheong·yongindae',
  '시흥능곡': 'siheungneunggok',
  '시흥대야': 'siheungdaeya',
  '시흥시청': 'siheungsicheong',
  '신갈': 'Singal',
  '신강일': 'singangil',
  '신금호': 'Singeumho',
  '신길': 'Singil',
  '신길온천': 'Singil Oncheon',
  '신내': 'sinnae',
  '신논현': 'Sinnonhyeon',
  '신답': 'Sindap',
  '신당': 'Sindang',
  '신대방': 'Sindaebang',
  '신대방삼거리': 'Sindaebangsamgeori',
  '신도림': 'Sindorim',
  '신둔도예촌': 'Sindundoyechon',
  '신림': 'Sillim',
  '신목동': 'Sinmokdong',
  '신반포': 'Sinbanpo',
  '신방화': 'Sinbanghwa',
  '신사': 'Sinsa',
  '신설동': 'Sinseol-dong',
  '신연수': 'Sinyeonsu',
  '신용산': 'Sinyongsan',
  '신원': 'Sinwon',
  '신이문': 'Sinimun',
  '신정': 'Sinjeong',
  '신정네거리': 'Sinjeongnegeori',
  '신중동': 'Sinjung-dong',
  '신창': 'Sinchang',
  '신천': 'Sincheon',
  '신촌': 'Sinchon',
  '신포': 'Sinpo',
  '신풍': 'Sinpung',
  '신현': 'sinhyeon',
  '신흥': 'Sinheung',
  '쌍문': 'Ssangmun',
  '쌍용': 'Ssangyong',
  '아라(북부법원경찰청)': 'Ara',
  '아산': 'Asan',
  '아시아드경기장': 'Asiad Stadium',
  '아신': 'Asin',
  '아차산': 'Achasan',
  '아현': 'Ahyeon',
  '안국': 'Anguk',
  '안산': 'Ansan',
  '안암': 'Anam',
  '안양': 'Anyang',
  '암사': 'Amsa',
  '암사역사공원': 'Amsa History Park',
  '압구정': 'Apgujeong',
  '압구정로데오': 'Apgujeongrodeo',
  '애오개': 'Aeogae',
  '야당': 'Yadang',
  '야목': 'Yamok',
  '야탑': 'Yatap',
  '약수': 'Yaksu',
  '양수': 'Yangsu',
  '양원': 'Yangwon',
  '양재': 'Yangjae',
  '양재시민의숲': 'Yangjae Citizen\'s Forest',
  '양정': 'Yangjeong',
  '양주': 'Yangju',
  '양천구청': 'Yangcheon-gu Office',
  '양천향교': 'Yangcheon Hyanggyo',
  '양촌': 'yangchon',
  '양평': 'Yangpyeong',
  '어룡': 'eoryong',
  '어린이대공원': 'Children\'s Grand Park',
  '어정': 'eojeong',
  '어천': 'Eocheon',
  '언주': 'Eonju',
  '여의나루': 'Yeouinaru',
  '여의도': 'Yeouido',
  '여주': 'Yeoju',
  '역곡': 'Yeokgok',
  '역삼': 'Yeoksam',
  '역촌': 'Yeokchon',
  '연수': 'Yeonsu',
  '연신내': 'Yeonsinnae',
  '연천': 'yeoncheon',
  '염창': 'Yeomchang',
  '영등포': 'Yeongdeungpo',
  '영등포구청': 'Yeongdeungpo-gu Office',
  '영등포시장': 'Yeongdeungpo Market',
  '영종': 'yeongjong',
  '영통': 'Yeongtong',
  '예술회관': 'Arts Center',
  '오금': 'Ogeum',
  '오남': 'Onam',
  '오류동': 'Oryu-dong',
  '오리': 'Ori',
  '오목교': 'Omokcheon',
  '오목천': 'Yadang',
  '오빈': 'Obin',
  '오산': 'Osan',
  '오산대': 'Osan College',
  '오이도': 'Oido',
  '옥수': 'Oksu',
  '온수': 'Onsu',
  '온양온천': 'Onyangoncheon',
  '올림픽공원': 'Olympic Park',
  '완정': 'Wanjeong',
  '왕길': 'Wanggil',
  '왕십리': 'Wangsimni',
  '외대앞': 'Hankuk University of Foreign Studies',
  '용답': 'Yongdap',
  '용두': 'Yongdu',
  '용마산': 'Yongmasan',
  '용문': 'Yongmun',
  '용산': 'Yongsan',
  '용인중앙시장': 'yonginjungangsijang',
  '우장산': 'Ujangsan',
  '운길산': 'Ungilsan',
  '운서': 'Unseo',
  '운양': 'unyang',
  '운연': 'Unyeon',
  '운정': 'Unjeong',
  '운정중앙': 'Unjeongjungang',
  '운천': 'uncheon',
  '원당': 'Wondang',
  '원덕': 'Wondeok',
  '원릉': 'wonreung',
  '원시': 'wonsi',
  '원인재': 'Woninjae',
  '원종': 'wonjong',
  '원흥': 'wonheung',
  '월계': 'Wolgye',
  '월곡': 'Wolgok',
  '월곶': 'Wolgot',
  '월드컵경기장': 'World Cup Stadium',
  '월롱': 'Wollong',
  '을지로3가': 'Euljiro 3(sam)-ga',
  '을지로4가': 'Euljiro 4(sa)-ga',
  '을지로입구': 'Euljiro 1(il)-ga',
  '응봉': 'Eungbong',
  '응암': 'Eungam',
  '의왕': 'Uiwang',
  '의정부': 'Uijeongbu',
  '의정부시청': 'uijeongbusicheong',
  '의정부중앙': 'uijeongbujungang',
  '이대': 'Ewha Womans University',
  '이매': 'Imae',
  '이수': 'Isu',
  '이천': 'Icheon',
  '이촌': 'Ichon',
  '이태원': 'Itaewon',
  '인덕원': 'Indeogwon',
  '인천': 'Incheon',
  '인천가좌': 'Incheon Gajwa',
  '인천공항1터미널': 'Incheon International Airport',
  '인천공항2터미널': 'incheongonghang2teomineol',
  '인천논현': 'Incheon Nonhyeon',
  '인천대공원': 'Incheon Grand Park',
  '인천대입구': 'University of Incheon',
  '인천시청': 'Incheon City Hall',
  '인천터미널': 'Incheon Bus Terminal',
  '인하대': 'Inha University',
  '일산': 'Ilsan',
  '일원': 'Irwon',
  '임진강': 'imjingang',
  '임학': 'Imhak',
  '자양': 'jayang',
  '작전': 'Jakjeon',
  '잠실': 'Jamsil',
  '잠실나루': 'Jamsillaru',
  '잠실새내': 'jamsilsaenae',
  '잠원': 'Jamwon',
  '장기': 'janggi',
  '장승배기': 'Jangseungbaegi',
  '장암': 'Jangam',
  '장지': 'Jangji',
  '장한평': 'Janghanpyeong',
  '전곡': 'jeongok',
  '전대·에버랜드': 'jeondae·ebeoraendeu',
  '정릉': 'jeongreung',
  '정발산': 'Jeongbalsan',
  '정부과천청사': 'Government Complex Gwacheon',
  '정왕': 'Jeongwang',
  '정자': 'Jeongja',
  '제기동': 'Jegi-dong',
  '제물포': 'Jemulpo',
  '종각': 'Jonggak',
  '종로3가': 'Jongno 3(sam)-ga',
  '종로5가': 'Jongno 5(o)-ga',
  '종합운동장': 'Sports Complex',
  '주안': 'Juan',
  '주안국가산단': 'Juan National Industrial Complex',
  '주엽': 'Juyeop',
  '죽전': 'Jukjeon',
  '중계': 'Junggye',
  '중곡': 'Junggok',
  '중동': 'Jung-dong',
  '중랑': 'Jungnang',
  '중앙보훈병원': 'VHS Medical Center',
  '중앙': 'Jungang',
  '중화': 'Junghwa',
  '증미': 'Jeungmi',
  '증산': 'Jeungsan',
  '지석': 'jiseok',
  '지식정보단지': 'BIT Zone',
  '지축': 'Jichuk',
  '지평': 'jipyeong',
  '지행': 'Jihaeng',
  '직산': 'Jiksan',
  '진위': 'Jinwi',
  '진접': 'Jinjeop',
  '창동': 'Chang-dong',
  '창신': 'Changsin',
  '천마산': 'cheonmasan',
  '천안': 'Cheonan',
  '천왕': 'Cheonwang',
  '천호': 'Cheonho',
  '철산': 'Cheolsan',
  '청계산입구': 'Cheonggyesan',
  '청구': 'Cheonggu',
  '청담': 'Cheongdam',
  '청라국제도시': 'cheongragukjedosi',
  '청량리': 'Cheongnyangni',
  '청명': 'Cheongmyeong',
  '청산': 'cheongsan',
  '청평': 'Cheongpyeong',
  '초당': 'chodang',
  '초월': 'Chowol',
  '초지': 'choji',
  '총신대입구(이수)': 'Chongshin Univ.(Isu)',
  '춘의': 'Chunui',
  '춘천': 'Chuncheon',
  '충무로': 'Chungmuro',
  '충정로': 'Chungjeongno',
  '캠퍼스타운': 'Campus Town',
  '킨텍스': 'Kintex',
  '탄현': 'Tanhyeon',
  '탑석': 'tapseok',
  '탕정': 'Tangjeong',
  '태릉입구': 'Taereung',
  '태평': 'Taepyeong',
  '테크노파크': 'Technopark',
  '퇴계원': 'Toegyewon',
  '파주': 'Paju',
  '판교': 'Pangyo',
  '팔당': 'Paldang',
  '평내호평': 'Pyeongnae-Hopyeong',
  '평촌': 'Pyeongchon',
  '평택': 'Pyeongtaek',
  '평택지제': 'Jije',
  '풍무': 'pungmu',
  '풍산': 'Pungsan',
  '하계': 'Hagye',
  '하남검단산': 'hanamgeomdansan',
  '하남시청': 'hanamsicheong',
  '하남풍산': 'hanampungsan',
  '학동': 'Hak-dong',
  '학여울': 'Hangnyeoul',
  '한강진': 'Hangangjin',
  '한국항공대': 'hangukhanggongdae',
  '한남': 'Hannam',
  '한대앞': 'Hanyang University at Ansan',
  '한성대입구': 'Hansung University',
  '한성백제': 'hanseongbaekje',
  '한양대': 'Hanyang University',
  '한티': 'Hanti',
  '합정': 'Hapjeong',
  '행당': 'Haengdang',
  '행신': 'Haengsin',
  '혜화': 'Hyehwa',
  '호구포': 'Hogupo',
  '홍대입구': 'Hongik University',
  '홍제': 'Hongje',
  '화계': 'hwagye',
  '화곡': 'Hwagok',
  '화랑대': 'Hwarangdae',
  '화서': 'Hwaseo',
  '화전': 'Hwajeon',
  '화정': 'Hwajeong',
  '회기': 'Hoegi',
  '회룡': 'Hoeryong',
  '회현': 'Hoehyeon',
  '효자': 'hyoja',
  '효창공원앞': 'Hyochang Park',
  '흑석': 'Heukseok',
  '흥선': 'heungseon',

  '전역': 'Prev. Station',
};

String translateStationName(String stationName) {
  return stationTranslationMap[stationName] ?? stationName;
}

/*String translateArrivalInfo(String ArrivalInfo) {
  ArrivalInfo.replaceAll('분', 'm').replaceAll('초', 's');
}*/
